"use client";
import React, { useState, useMemo } from "react";
import { Search } from "lucide-react";
import ServiceSidebar from "./ServiceSidebar";
import ServiceGrid from "./ServiceGrid";
import { Product } from "./ServiceCard";

// Mock data - Replace with API call
const MOCK_PRODUCTS: Product[] = [
  // Vegetables
  {
    id: "v1",
    name: "Red Tomatoes",
    category: "Vegetables",
    image: "/red-tomatoes.png",
    rating: 4.5,
    reviewCount: 120,
    price: 2.5,
    unit: "Pound",
    description: "Fresh, vine-ripened organic red tomatoes.",
    priceHigh: 3.5,
    priceMedium: 2.5,
    priceLow: 1.5,
  },
  {
    id: "v2",
    name: "Carrots",
    category: "Vegetables",
    image: "/carrots.png",
    rating: 4.8,
    reviewCount: 85,
    price: 1.8,
    unit: "Pound",
    description: "Fresh, crunchy organic carrots with tops.",
    priceHigh: 2.8,
    priceMedium: 1.8,
    priceLow: 0.8,
  },
  {
    id: "v3",
    name: "Fresh Broccoli",
    category: "Vegetables",
    image: "/broccoli.png",
    rating: 4.7,
    reviewCount: 92,
    price: 3.2,
    unit: "Pound",
    description: "Nutritious organic broccoli florets.",
    priceHigh: 4.2,
    priceMedium: 3.2,
    priceLow: 2.2,
  },
  {
    id: "v4",
    name: "Bell Peppers",
    category: "Vegetables",
    image: "/bell-peppers.png",
    rating: 4.6,
    reviewCount: 78,
    price: 2.8,
    unit: "Pound",
    description: "Colorful organic bell peppers.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },
  {
    id: "v5",
    name: "Cucumbers",
    category: "Vegetables",
    image: "/cucumbers.png",
    rating: 4.4,
    reviewCount: 64,
    price: 1.5,
    unit: "Pound",
    description: "Fresh and crisp organic cucumbers.",
    priceHigh: 2.5,
    priceMedium: 1.5,
    priceLow: 0.5,
  },
  {
    id: "v6",
    name: "Zucchini",
    category: "Vegetables",
    image: "/zucchini.png",
    rating: 4.3,
    reviewCount: 52,
    price: 2.2,
    unit: "Pound",
    description: "Tender organic zucchini.",
    priceHigh: 3.2,
    priceMedium: 2.2,
    priceLow: 1.2,
  },
  {
    id: "v7",
    name: "Red Onions",
    category: "Vegetables",
    image: "/category-1.png",
    rating: 4.5,
    reviewCount: 110,
    price: 1.2,
    unit: "Pound",
    description: "Sharp and sweet red onions.",
    priceHigh: 2.2,
    priceMedium: 1.2,
    priceLow: 0.6,
  },
  {
    id: "v8",
    name: "Potatoes",
    category: "Vegetables",
    image: "/category-1.png",
    rating: 4.9,
    reviewCount: 230,
    price: 0.8,
    unit: "Pound",
    description: "Versatile organic russet potatoes.",
    priceHigh: 1.8,
    priceMedium: 0.8,
    priceLow: 0.4,
  },
  {
    id: "v9",
    name: "Garlic",
    category: "Vegetables",
    image: "/category-1.png",
    rating: 4.7,
    reviewCount: 145,
    price: 3.5,
    unit: "Pound",
    description: "Aromatic organic garlic bulbs.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },
  {
    id: "v10",
    name: "Eggplant",
    category: "Vegetables",
    image: "/category-1.png",
    rating: 4.2,
    reviewCount: 41,
    price: 2.9,
    unit: "Pound",
    description: "Glossy organic purple eggplant.",
    priceHigh: 3.9,
    priceMedium: 2.9,
    priceLow: 1.9,
  },

  // Fruits
  {
    id: "f1",
    name: "Fresh Apples",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.8,
    reviewCount: 156,
    price: 3.0,
    unit: "Pound",
    description: "Crisp and sweet organic apples.",
    priceHigh: 4.0,
    priceMedium: 3.0,
    priceLow: 2.0,
  },
  {
    id: "f2",
    name: "Bananas",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.9,
    reviewCount: 312,
    price: 0.6,
    unit: "Pound",
    description: "Ripe organic yellow bananas.",
    priceHigh: 1.6,
    priceMedium: 0.6,
    priceLow: 0.3,
  },
  {
    id: "f3",
    name: "Strawberries",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.7,
    reviewCount: 89,
    price: 4.5,
    unit: "Box",
    description: "Sweet fresh strawberries.",
    priceHigh: 5.5,
    priceMedium: 4.5,
    priceLow: 3.5,
  },
  {
    id: "f4",
    name: "Oranges",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.6,
    reviewCount: 124,
    price: 2.2,
    unit: "Pound",
    description: "Juicy organic oranges.",
    priceHigh: 3.2,
    priceMedium: 2.2,
    priceLow: 1.2,
  },
  {
    id: "f5",
    name: "Grapes",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.5,
    reviewCount: 98,
    price: 3.8,
    unit: "Pound",
    description: "Seedless sweet organic grapes.",
    priceHigh: 4.8,
    priceMedium: 3.8,
    priceLow: 2.8,
  },
  {
    id: "f6",
    name: "Mangoes",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.9,
    reviewCount: 175,
    price: 1.5,
    unit: "Each",
    description: "Sweet tropical mangoes.",
    priceHigh: 2.5,
    priceMedium: 1.5,
    priceLow: 0.8,
  },
  {
    id: "f7",
    name: "Pineapple",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.8,
    reviewCount: 63,
    price: 4.0,
    unit: "Each",
    description: "Fresh golden pineapple.",
    priceHigh: 5.0,
    priceMedium: 4.0,
    priceLow: 3.0,
  },
  {
    id: "f8",
    name: "Blueberries",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.7,
    reviewCount: 82,
    price: 5.2,
    unit: "Box",
    description: "Antioxidant-rich blueberries.",
    priceHigh: 6.2,
    priceMedium: 5.2,
    priceLow: 4.2,
  },
  {
    id: "f9",
    name: "Watermelon",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.6,
    reviewCount: 45,
    price: 6.0,
    unit: "Each",
    description: "Large sweet watermelon.",
    priceHigh: 8.0,
    priceMedium: 6.0,
    priceLow: 4.0,
  },
  {
    id: "f10",
    name: "Pears",
    category: "Fruits",
    image: "/category-2.png",
    rating: 4.4,
    reviewCount: 57,
    price: 2.8,
    unit: "Pound",
    description: "Juicy organic pears.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },

  // Greens
  {
    id: "g1",
    name: "Spinach",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.6,
    reviewCount: 74,
    price: 1.8,
    unit: "Pound",
    description: "Fresh organic spinach leaves.",
    priceHigh: 2.8,
    priceMedium: 1.8,
    priceLow: 0.8,
  },
  {
    id: "g2",
    name: "Kale",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.7,
    reviewCount: 58,
    price: 2.5,
    unit: "Bunch",
    description: "Nutritious organic curly kale.",
    priceHigh: 3.5,
    priceMedium: 2.5,
    priceLow: 1.5,
  },
  {
    id: "g3",
    name: "Lettuce",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.5,
    reviewCount: 112,
    price: 1.5,
    unit: "Each",
    description: "Crisp romaine lettuce.",
    priceHigh: 2.5,
    priceMedium: 1.5,
    priceLow: 0.75,
  },
  {
    id: "g4",
    name: "Arugula",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.4,
    reviewCount: 42,
    price: 3.0,
    unit: "Pack",
    description: "Peppery organic arugula.",
    priceHigh: 4.0,
    priceMedium: 3.0,
    priceLow: 2.0,
  },
  {
    id: "g5",
    name: "Swiss Chard",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.6,
    reviewCount: 31,
    price: 2.8,
    unit: "Bunch",
    description: "Fresh organic swiss chard.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },
  {
    id: "g6",
    name: "Collard Greens",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.3,
    reviewCount: 25,
    price: 2.2,
    unit: "Bunch",
    description: "Organic collard greens.",
    priceHigh: 3.2,
    priceMedium: 2.2,
    priceLow: 1.2,
  },
  {
    id: "g7",
    name: "Bok Choy",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.7,
    reviewCount: 39,
    price: 3.5,
    unit: "Pound",
    description: "Baby organic bok choy.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },
  {
    id: "g8",
    name: "Cabbage",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.8,
    reviewCount: 88,
    price: 1.2,
    unit: "Each",
    description: "Fresh green cabbage.",
    priceHigh: 2.2,
    priceMedium: 1.2,
    priceLow: 0.6,
  },
  {
    id: "g9",
    name: "Parsley",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.9,
    reviewCount: 65,
    price: 1.0,
    unit: "Bunch",
    description: "Fresh organic parsley.",
    priceHigh: 2.0,
    priceMedium: 1.0,
    priceLow: 0.5,
  },
  {
    id: "g10",
    name: "Cilantro",
    category: "Greens",
    image: "/category-3.png",
    rating: 4.8,
    reviewCount: 125,
    price: 1.0,
    unit: "Bunch",
    description: "Fresh organic cilantro.",
    priceHigh: 2.0,
    priceMedium: 1.0,
    priceLow: 0.5,
  },

  // Dairy
  {
    id: "d1",
    name: "Whole Milk",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.7,
    reviewCount: 245,
    price: 4.5,
    unit: "Gallon",
    description: "Fresh whole milk from local farms.",
    priceHigh: 5.5,
    priceMedium: 4.5,
    priceLow: 3.5,
  },
  {
    id: "d2",
    name: "Greek Yogurt",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.8,
    reviewCount: 156,
    price: 5.5,
    unit: "Tub",
    description: "Creamy organic greek yogurt.",
    priceHigh: 6.5,
    priceMedium: 5.5,
    priceLow: 4.5,
  },
  {
    id: "d3",
    name: "Butter",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.9,
    reviewCount: 189,
    price: 3.8,
    unit: "Pack",
    description: "Farm fresh salted butter.",
    priceHigh: 4.8,
    priceMedium: 3.8,
    priceLow: 2.8,
  },
  {
    id: "d4",
    name: "Heavy Cream",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.7,
    reviewCount: 67,
    price: 4.2,
    unit: "Quart",
    description: "Rich organic heavy cream.",
    priceHigh: 5.2,
    priceMedium: 4.2,
    priceLow: 3.2,
  },
  {
    id: "d5",
    name: "Sour Cream",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.6,
    reviewCount: 82,
    price: 2.5,
    unit: "Tub",
    description: "Fresh organic sour cream.",
    priceHigh: 3.5,
    priceMedium: 2.5,
    priceLow: 1.5,
  },
  {
    id: "d6",
    name: "Cottage Cheese",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.5,
    reviewCount: 54,
    price: 3.9,
    unit: "Tub",
    description: "High-protein cottage cheese.",
    priceHigh: 4.9,
    priceMedium: 3.9,
    priceLow: 2.9,
  },
  {
    id: "d7",
    name: "Almond Milk",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.7,
    reviewCount: 128,
    price: 4.0,
    unit: "Carton",
    description: "Unsweetened organic almond milk.",
    priceHigh: 5.0,
    priceMedium: 4.0,
    priceLow: 3.0,
  },
  {
    id: "d8",
    name: "Soy Milk",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.6,
    reviewCount: 91,
    price: 3.8,
    unit: "Carton",
    description: "Organic vanilla soy milk.",
    priceHigh: 4.8,
    priceMedium: 3.8,
    priceLow: 2.8,
  },
  {
    id: "d9",
    name: "Chocolate Milk",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.9,
    reviewCount: 73,
    price: 2.8,
    unit: "Bottle",
    description: "Rich chocolate dairy milk.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },
  {
    id: "d10",
    name: "Whipped Cream",
    category: "Dairy",
    image: "/category-4.png",
    rating: 4.8,
    reviewCount: 42,
    price: 3.5,
    unit: "Can",
    description: "Real dairy whipped cream.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },

  // Dry Groceries
  {
    id: "dg1",
    name: "Basmati Rice",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.9,
    reviewCount: 142,
    price: 12.0,
    unit: "5lb Bag",
    description: "Premium aged basmati rice.",
    priceHigh: 13.0,
    priceMedium: 12.0,
    priceLow: 11.0,
  },
  {
    id: "dg2",
    name: "Red Lentils",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.8,
    reviewCount: 88,
    price: 3.5,
    unit: "2lb Bag",
    description: "Organic split red lentils.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },
  {
    id: "dg3",
    name: "Chickpeas",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.7,
    reviewCount: 76,
    price: 2.8,
    unit: "2lb Bag",
    description: "Dried organic chickpeas.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },
  {
    id: "dg4",
    name: "Quinoa",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.8,
    reviewCount: 65,
    price: 8.5,
    unit: "2lb Bag",
    description: "Organic white quinoa.",
    priceHigh: 9.5,
    priceMedium: 8.5,
    priceLow: 7.5,
  },
  {
    id: "dg5",
    name: "Rolled Oats",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.7,
    reviewCount: 124,
    price: 4.2,
    unit: "Bag",
    description: "Old fashioned rolled oats.",
    priceHigh: 5.2,
    priceMedium: 4.2,
    priceLow: 3.2,
  },
  {
    id: "dg6",
    name: "Brown Sugar",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.6,
    reviewCount: 53,
    price: 2.5,
    unit: "Bag",
    description: "Organic light brown sugar.",
    priceHigh: 3.5,
    priceMedium: 2.5,
    priceLow: 1.5,
  },
  {
    id: "dg7",
    name: "All-Purpose Flour",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.8,
    reviewCount: 210,
    price: 5.0,
    unit: "5lb Bag",
    description: "Organic unbleached flour.",
    priceHigh: 6.0,
    priceMedium: 5.0,
    priceLow: 4.0,
  },
  {
    id: "dg8",
    name: "Sea Salt",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.9,
    reviewCount: 145,
    price: 4.8,
    unit: "Jar",
    description: "Fine grain mediterranean sea salt.",
    priceHigh: 5.8,
    priceMedium: 4.8,
    priceLow: 3.8,
  },
  {
    id: "dg9",
    name: "Black Pepper",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.8,
    reviewCount: 82,
    price: 6.5,
    unit: "Jar",
    description: "Whole black peppercorns.",
    priceHigh: 7.5,
    priceMedium: 6.5,
    priceLow: 5.5,
  },
  {
    id: "dg10",
    name: "Spice Mix",
    category: "Dry Groceries",
    image: "/category-5.png",
    rating: 4.7,
    reviewCount: 34,
    price: 5.8,
    unit: "Jar",
    description: "Organic italian herb seasoning.",
    priceHigh: 6.8,
    priceMedium: 5.8,
    priceLow: 4.8,
  },

  // Pantry
  {
    id: "p1",
    name: "Organic Pasta",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.5,
    reviewCount: 142,
    price: 3.5,
    unit: "Box",
    description: "Artisan durum wheat pasta.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },
  {
    id: "p2",
    name: "Tomato Sauce",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.6,
    reviewCount: 96,
    price: 4.2,
    unit: "Jar",
    description: "Organic basil tomato sauce.",
    priceHigh: 5.2,
    priceMedium: 4.2,
    priceLow: 3.2,
  },
  {
    id: "p3",
    name: "Olive Oil",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.9,
    reviewCount: 187,
    price: 15.0,
    unit: "Bottle",
    description: "Extra virgin cold pressed olive oil.",
    priceHigh: 16.0,
    priceMedium: 15.0,
    priceLow: 14.0,
  },
  {
    id: "p4",
    name: "Raw Honey",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.9,
    reviewCount: 124,
    price: 12.5,
    unit: "Jar",
    description: "Unfiltered organic raw honey.",
    priceHigh: 13.5,
    priceMedium: 12.5,
    priceLow: 11.5,
  },
  {
    id: "p5",
    name: "Peanut Butter",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.7,
    reviewCount: 156,
    price: 6.8,
    unit: "Jar",
    description: "Creamy organic peanut butter.",
    priceHigh: 7.8,
    priceMedium: 6.8,
    priceLow: 5.8,
  },
  {
    id: "p6",
    name: "Strawberry Jam",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.6,
    reviewCount: 78,
    price: 5.2,
    unit: "Jar",
    description: "Organic strawberry preserves.",
    priceHigh: 6.2,
    priceMedium: 5.2,
    priceLow: 4.2,
  },
  {
    id: "p7",
    name: "Crackers",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.4,
    reviewCount: 63,
    price: 3.9,
    unit: "Box",
    description: "Whole grain organic crackers.",
    priceHigh: 4.9,
    priceMedium: 3.9,
    priceLow: 2.9,
  },
  {
    id: "p8",
    name: "Canned Beans",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.5,
    reviewCount: 231,
    price: 1.5,
    unit: "Can",
    description: "Organic black beans.",
    priceHigh: 2.5,
    priceMedium: 1.5,
    priceLow: 0.75,
  },
  {
    id: "p9",
    name: "Canned Tuna",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.3,
    reviewCount: 89,
    price: 2.8,
    unit: "Can",
    description: "Wild caught albacore tuna.",
    priceHigh: 3.8,
    priceMedium: 2.8,
    priceLow: 1.8,
  },
  {
    id: "p10",
    name: "Vegetable Soup",
    category: "Pantry",
    image: "/category-5.png",
    rating: 4.2,
    reviewCount: 45,
    price: 3.5,
    unit: "Can",
    description: "Organic hearty vegetable soup.",
    priceHigh: 4.5,
    priceMedium: 3.5,
    priceLow: 2.5,
  },

  // Cheese
  {
    id: "c1",
    name: "Cheddar Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.8,
    reviewCount: 165,
    price: 6.0,
    unit: "8oz",
    description: "Aged sharp cheddar cheese.",
    priceHigh: 7.0,
    priceMedium: 6.0,
    priceLow: 5.0,
  },
  {
    id: "c2",
    name: "Mozzarella",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.9,
    reviewCount: 212,
    price: 5.5,
    unit: "8oz",
    description: "Fresh organic mozzarella ball.",
    priceHigh: 6.5,
    priceMedium: 5.5,
    priceLow: 4.5,
  },
  {
    id: "c3",
    name: "Parmesan",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.9,
    reviewCount: 145,
    price: 8.5,
    unit: "8oz",
    description: "Aged italian parmesan wedge.",
    priceHigh: 9.5,
    priceMedium: 8.5,
    priceLow: 7.5,
  },
  {
    id: "c4",
    name: "Feta Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.7,
    reviewCount: 98,
    price: 4.8,
    unit: "8oz",
    description: "Creamy organic sheep feta.",
    priceHigh: 5.8,
    priceMedium: 4.8,
    priceLow: 3.8,
  },
  {
    id: "c5",
    name: "Brie Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.8,
    reviewCount: 76,
    price: 7.2,
    unit: "8oz",
    description: "Double cream organic brie.",
    priceHigh: 8.2,
    priceMedium: 7.2,
    priceLow: 6.2,
  },
  {
    id: "c6",
    name: "Gouda",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.7,
    reviewCount: 54,
    price: 6.5,
    unit: "8oz",
    description: "Mild smoked organic gouda.",
    priceHigh: 7.5,
    priceMedium: 6.5,
    priceLow: 5.5,
  },
  {
    id: "c7",
    name: "Blue Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.4,
    reviewCount: 42,
    price: 5.9,
    unit: "4oz",
    description: "Crumble blue cheese wedge.",
    priceHigh: 6.9,
    priceMedium: 5.9,
    priceLow: 4.9,
  },
  {
    id: "c8",
    name: "Swiss Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.6,
    reviewCount: 67,
    price: 5.2,
    unit: "8oz",
    description: "Organic swiss cheese slices.",
    priceHigh: 6.2,
    priceMedium: 5.2,
    priceLow: 4.2,
  },
  {
    id: "c9",
    name: "Goat Cheese",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.8,
    reviewCount: 83,
    price: 6.8,
    unit: "4oz",
    description: "Fresh organic goat cheese log.",
    priceHigh: 7.8,
    priceMedium: 6.8,
    priceLow: 5.8,
  },
  {
    id: "c10",
    name: "Provolone",
    category: "Cheese",
    image: "/category-4.png",
    rating: 4.5,
    reviewCount: 51,
    price: 4.5,
    unit: "8oz",
    description: "Mild organic provolone slices.",
    priceHigh: 5.5,
    priceMedium: 4.5,
    priceLow: 3.5,
  },
];

const PRICE_TIERS = ["Category 1", "Category 2", "Category 3"];
const PRODUCT_CATEGORIES = [
  "Vegetables",
  "Fruits",
  "Greens",
  "Dairy",
  "Dry Groceries",
  "Pantry",
  "Cheese",
];

interface ServicePageProps {
  initialProducts?: Product[];
}

export default function ServicePage({
  initialProducts = MOCK_PRODUCTS,
}: ServicePageProps) {
  const [selectedPriceTier, setSelectedPriceTier] =
    useState<string>("Category 1");
  const [selectedCategory, setSelectedCategory] =
    useState<string>("Vegetables");
  const [searchTerm, setSearchTerm] = useState<string>("");

  const filteredProducts = useMemo(() => {
    const byCategory = initialProducts.filter(
      (product) => product.category === selectedCategory
    );

    if (!searchTerm.trim()) {
      return byCategory;
    }

    const term = searchTerm.toLowerCase();
    return byCategory.filter(
      (product) =>
        product.name.toLowerCase().includes(term) ||
        product.description.toLowerCase().includes(term)
    );
  }, [selectedCategory, initialProducts, searchTerm]);

  const activeTier =
    selectedPriceTier === "Category 1"
      ? "high"
      : selectedPriceTier === "Category 2"
      ? "medium"
      : "low";

  return (
    <section className="py-12 bg-gray-50 min-h-screen">
      <div className="container mx-auto px-4">
        <div className="mb-8 flex flex-col items-center gap-4 text-center">
          <div>
            <h1 className="text-2xl font-bold text-[#1A2D42] md:text-3xl">
              Browse fresh products
            </h1>
            <p className="text-sm text-gray-500">
              Filter by category, price tier, or search by name.
            </p>
          </div>
          <form
            className="w-full max-w-xl"
            onSubmit={(e) => {
              e.preventDefault();
            }}
          >
            <div className="relative flex w-full items-center gap-2">
              <div className="relative flex-1 w-full rounded-2xl border border-gray-200 bg-white/90 shadow-sm transition-all duration-500 ease-out focus-within:bg-white focus-within:shadow-lg focus-within:shadow-[#004F3B]/10 focus-within:border-[#004F3B]">
                <Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400 transition-colors duration-300 focus-within:text-[#004F3B]" />
                <input
                  type="text"
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  placeholder="Search fresh produce....."
                  className="w-full rounded-2xl bg-transparent py-2.5 pl-10 pr-3 text-sm text-gray-800 placeholder:text-gray-400 focus:outline-none"
                />
              </div>
              <button
                type="submit"
                className="whitespace-nowrap rounded-2xl bg-[#004F3B] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-all duration-300 hover:bg-[#003528] hover:shadow-md"
              >
                Search
              </button>
            </div>
          </form>
        </div>
        <div className="flex flex-col lg:flex-row gap-8">
          <ServiceSidebar
            priceTiers={PRICE_TIERS}
            selectedPriceTier={selectedPriceTier}
            onSelectPriceTier={setSelectedPriceTier}
            productCategories={PRODUCT_CATEGORIES}
            selectedCategory={selectedCategory}
            onSelectCategory={setSelectedCategory}
          />
          <ServiceGrid products={filteredProducts} activeTier={activeTier} />
        </div>
      </div>
    </section>
  );
}
